src/EcommerceBundle/Form/SearchType.php
<?php

namespace EcommerceBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $option)
    {
        $builder->add('search', TextType::class, [
            'label' => false,
            'attr'  => ['class' => 'input-medium search-query'],
        ]);
    }

    public function getName()
    {
        return 'ecommercebundle_search';
    }
}

src/EcommerceBundle/Resources/views/categories.html.twig
{% for category in  categories %}
    <li><a href="{{ path('category_products', {'category' : category.id}) }}">{{ category.name|capitalize }}</a></li>
{% endfor %}

src/EcommerceBundle/Resources/views/col-left-co.html.twig
<div class="span3">

    <div class="well">
        <ul class="nav nav-list">
            <li>
                <a href="{{ path('fos_user_profile_show') }}">Mes informations</a>
            </li>
            <li>
                <a href="{{ path('fos_user_profile_edit') }}">Editer mes informations</a>
            </li>
            <li>
                <a href="{{ path('fos_user_change_password') }}">Changer mon mot de passe</a>
            </li>
            <li>
                <a href="{{ path('bill') }}">Mes factures</a>
            </li>

            <li>
                <a href="{{ path('fos_user_security_logout') }}">Deconnexion</a>
            </li>
        </ul>
    </div>
    {{ render(controller('EcommerceBundle:Basket:menu')) }}

    <div class="well">
        <ul class="nav nav-list">
            <li class="nav-header">Nos produits</li>
            {{ render(controller('EcommerceBundle:Category:menuCategories')) }}
        </ul>
    </div>

</div>

src/EcommerceBundle/Resources/views/col-left.html.twig
<div class="span3">
    {{ render(controller('EcommerceBundle:Basket:menu')) }}

    <div class="well">
        <ul class="nav nav-list">
            <li>
                <a href="{{ path('fos_user_security_login') }}">Se connecter</a>
            </li>
            <li>
                <a href="{{ path('fos_user_registration_register') }}">S'inscrire</a>
            </li>
        </ul>
    </div>

    <div class="well">
        <ul class="nav nav-list">
            <li class="nav-header">Nos produits</li>
            {{ render(controller('EcommerceBundle:Category:menuCategories')) }}
        </ul>
    </div>
</div>

src/EcommerceBundle/Resources/views/layout.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Ecommerce{% endblock %}</title>
    <meta name="keywords" content="{% block metaKeyWords %} {% endblock %}">
    <meta name="description" content="{% block metaDescription %} {% endblock %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css"
          rel="stylesheet" integrity="sha384-4FeI0trTH/PCsLWrGCD1mScoFu9Jf2NdknFdFoJhXZFwsvzZ3Bo5sAh7+zL8Xgnd"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{{ path('ecommerce_homepage') }}">Ecommerce</a>
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('admin') }}" class="brand">  Administration</a>
            {% endif %}
            <div class="nav-collapse collapse">
                {{ render(controller('EcommerceBundle:Product:search')) }}
            </div>
        </div>
    </div>
</div>
<hr/>
{% block body %} {% endblock %}
<footer id="footer" class="vspace20">
    <div class="container">
        <div class="row">
            <div class="span4 offset1">
                <h4>Informations</h4>
                <ul class="nav nav-stacked">
                    <li><a href="#">CGV</a>
                    <li><a href="#">Mentions légales</a>
                </ul>
            </div>

            <div class="span4">
                <h4>Notre entrepôt</h4>
                <p><i class="icon-map-marker"></i> Grenoble</p>
            </div>

            <div class="span2">
                <h4>Nous contacter</h4>
                <p></i>&nbsp;Tel: {{ tel }}</p>
                <p></i>&nbsp;Fax: {{ fax }}</p>
            </div>
        </div>

        <div class="row">
            <div class="span4">
                <p>Exercice démo Symfony</p>
            </div>
        </div>
    </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{{ asset('js/main.js') }}"></script>
<script src="https://stackpath.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"
        integrity="sha384-vOWIrgFbxIPzY09VArRHMsxned7WiY6hzIPtAIIeTFuii9y3Cr6HE6fcHXy5CFhc"
        crossorigin="anonymous"></script>
<script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
{% block javascript %} {% endblock %}
</body>
</html>