src/EcommerceBundle/Entity/Media.php
<?php

namespace EcommerceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraint as Assert;
use Symfony\Component\Validator\Constraints\Callback;

/**
 * Media
 *
 * @ORM\Table(name="media")
 * @ORM\Entity(repositoryClass="EcommerceBundle\Repository\MediaRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Media
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    public function getFile()
    {
        return $this->file;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUrl()
    {
        return $this->url;
    }
    public function getAlt()
    {
        return $this->alt;
    }

    private $file;

    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/EcommerceBundle/Entity/Product.php
<?php

namespace EcommerceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="EcommerceBundle\Repository\ProductRepository")
 */
class Product
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;

    /**
     * @var bool
     *
     * @ORM\Column(name="available", type="boolean")
     */
    private $available;

    /**
     * @var string
     *
     *
     * @ORM\ManyToOne(targetEntity="EcommerceBundle\Entity\Category", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @var string
     *
     *
     * @ORM\OneToOne(targetEntity="EcommerceBundle\Entity\Media", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $image;


    /**
     * @var float
     *
     *
     * @ORM\ManyToOne(targetEntity="EcommerceBundle\Entity\Taxe", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $taxe;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set price
     *
     * @param float $price
     *
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set available
     *
     * @param boolean $available
     *
     * @return Product
     */
    public function setAvailable($available)
    {
        $this->available = $available;

        return $this;
    }

    /**
     * Get available
     *
     * @return bool
     */
    public function getAvailable()
    {
        return $this->available;
    }

    /**
     * Set category
     *
     * @param string $category
     *
     * @return Product
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return Product
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set taxe
     *
     * @param float $taxe
     *
     * @return Product
     */
    public function setTaxe($taxe)
    {
        $this->taxe = $taxe;

        return $this;
    }

    /**
     * Get taxe
     *
     * @return float
     */
    public function getTaxe()
    {
        return $this->taxe;
    }
}

src/EcommerceBundle/Form/ProductType.php
<?php

namespace EcommerceBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use EcommerceBundle\Form\MediaType;

class ProductType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name')->add('description')->add('price')->add('available')->add('category')->add('image', MediaType::class)->add('taxe');
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'EcommerceBundle\Entity\Product'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ecommercebundle_product';
    }


}

src/EcommerceBundle/Controller/ProductController.php
<?php

namespace EcommerceBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use EcommerceBundle\Entity\Product;
use EcommerceBundle\Form\SearchType;
use Symfony\Component\HttpFoundation\Request;
use EcommerceBundle\Repository\ProductRepository;
use EcommerceBundle\Entity\Category;
use Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter;

class ProductController extends Controller
{
    public function indexAction(Request $request, Category $category = null)
    {
        $session = $request->getSession();
        $em = $this->getDoctrine()->getManager();

        if ($category != null) {
            $productsQuery = $em->getRepository(Product::class)->findBy(['category' => $category, 'available' => 1]);
        } else {
            $productsQuery = $em->getRepository(Product::class)->findBy(['available' => 1]);
        }

        if ($session->has('basket')) {
            $basket = $session->get('basket');
        } else {
            $basket = false;
        }

        $paginator = $this->get('knp_paginator');
        $products = $paginator->paginate(
            $productsQuery, /* query NOT result */
            $request->query->getInt('page', 1) /*page number*/,
            2/*limit per page*/
        );


        return $this->render('EcommerceBundle:Product:index.html.twig',
            ['basket' => $basket, 'products' => $products]);
    }

    public function viewAction($id, Request $request)
    {
        $session = $request->getSession();

        $em = $this->getDoctrine()->getManager();
        $product = $em->getRepository(Product::class)->find($id);

        if (!$product) {
            throw $this->createNotFoundException('La page n\'existe pas.');
        }

        if ($session->has('basket')) {
            $basket = $session->get('basket');
        } else {
            $basket = false;
        }

        return $this->render('EcommerceBundle:Product:view.html.twig', ['product' => $product, 'basket' => $basket]);
    }

    public function searchAction()
    {
        $form = $this->createForm(SearchType::class);

        return $this->render('EcommerceBundle:Product:search.html.twig', ['form' => $form->createView()]);

    }

    public function searchResultAction(Request $request)
    {
        $form = $this->createForm(SearchType::class);

        if ($request->isMethod('POST')) {
            $form->submit($request->request->get($form->getName()));

            if ($form->isSubmitted() && $form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $productsResult = $em->getRepository('EcommerceBundle:Product')->search($form['search']->getData());

                $paginator = $this->get('knp_paginator');
                $products = $paginator->paginate(
                    $productsResult, /* query NOT result */
                    $request->query->getInt('page', 1) /*page number*/,
                    400/*limit per page*/
                );
            } else {
                throw $this->createNotFoundException('Le produit n\'existe pas.');
            }

 //  Probleme en get page n'existe pas, pas de recherche avec pagination ( limit per page du paginator elevee pour eviter plusieurs pages
//            et donc eviter passage en get  = pas de pagination avec la recherche )
            return $this->render('EcommerceBundle:Product:index.html.twig', ['products' => $products]);
        } else {
            throw $this->createNotFoundException('La page n\'existe pas.');
        }

    }
}

src/EcommerceBundle/Resources/views/Product/index.html.twig
{% extends "EcommerceBundle::layout.html.twig" %}
{% block body %}
    <div class="container">
        <div class="row">
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                {% include  "EcommerceBundle::col-left-co.html.twig" %}
            {% else %}
                {% include  "EcommerceBundle::col-left.html.twig" %}
            {% endif %}
            <div class="span9">
                {% if products|length != 0 %}
                    <ul class="thumbnails">
                        {% for product in products %}
                            <li class="span3">
                                <div class="thumbnail">
                                    <img src="{{ asset(product.image.webPath) }}" alt="{{ product.image.alt }}" width="300"
                                         height="300">
                                    <div class="caption">
                                        <h4>{{ product.name }}</h4>
                                        <p>{{ product.price|taxe(product.taxe.rate) }} €</p>
                                        <a class="btn btn-primary"
                                           href="{{ path('ecommerce_product', {'id' : product.id}) }}">Plus d'infos</a>
                                        {% if basket[product.id] is not defined %}
                                            <a class="btn btn-success"
                                               href="{{ path('add_basket', {'id' : product.id}) }}">Ajouter au
                                                panier</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>

                    <div class="navigation text-center">
                        {{ knp_pagination_render(products) }}
                    </div>


                {% else %}
                    <p> Aucun produit</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

src/EcommerceBundle/Resources/views/Product/search.html.twig
<form action="{{ path('search_product') }}" method="POST" class="navbar-form form-search pull-right">
    {{ form_widget(form.search) }}
    <button type="submit" class="btn">Rechercher</button>
    {{ form_rest(form) }}
</form>

src/EcommerceBundle/Resources/views/Product/view.html.twig
{% extends "EcommerceBundle::layout.html.twig" %}
{% block title %} {{ product.name }} {% endblock %}
{% block metaDescription %} {{ product.description }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                {% include  "EcommerceBundle::col-left-co.html.twig" %}
            {% else %}
                {% include  "EcommerceBundle::col-left.html.twig" %}
            {% endif %}
            <div class="span9">
                <div class="row">
                    <div class="span5">
                        <img src="{{ asset(product.image.webPath) }}" alt="{{ product.image.alt }}" width="470" height="310">
                    </div>

                    <div class="span4">
                        <h4>{{ product.name }}</h4>
                        <h5>{{ product.category.name|capitalize }}</h5>
                        <p>{{ product.description|nl2br }}</p>
                        <h4>{{ product.price|taxe(product.taxe.rate) }}€</h4>
                        {% if basket[product.id] is not defined %}
                            <form action="{{ path('add_basket', {'id' : product.id}) }}" method="GET">
                                <select name="qte" class="span1">
                                    {% for i in 1..10 %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                                <div>
                                    <button class="btn btn-primary">Ajouter au panier</button>
                                </div>
                            </form>
                        {% else %}
                            <div>
                                <a href="{{ path('ecommerce_basket') }}">Le produit est déjà au panier</a>
                            </div>
                        {% endif %}
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}